
package com.contractfirstexample.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.contractfirstexample.domain.Book;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IBookService", targetNamespace = "http://service.contractfirstexample.com")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.contractfirstexample.domain.ObjectFactory.class,
    com.contractfirstexample.service.ObjectFactory.class
})
public interface IBookService {


    /**
     * 
     * @param isbn
     * @return
     *     returns com.contractfirstexample.domain.Book
     */
    @WebMethod
    @WebResult(name = "searchBookReturn", targetNamespace = "http://service.contractfirstexample.com", partName = "book")
    public Book searchBook(
        @WebParam(name = "isbn", targetNamespace = "http://service.contractfirstexample.com", partName = "isbn")
        int isbn);

}
