
package com.bookserviceproviderexample.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BookWebServiceImplService", targetNamespace = "http://service.bookserviceproviderexample.com/", wsdlLocation = "http://localhost:8082/Book_Service_Provider_Example/searchBooks?wsdl")
public class BookWebServiceImplService
    extends Service
{

    private final static URL BOOKWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException BOOKWEBSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName BOOKWEBSERVICEIMPLSERVICE_QNAME = new QName("http://service.bookserviceproviderexample.com/", "BookWebServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8082/Book_Service_Provider_Example/searchBooks?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BOOKWEBSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        BOOKWEBSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public BookWebServiceImplService() {
        super(__getWsdlLocation(), BOOKWEBSERVICEIMPLSERVICE_QNAME);
    }

    public BookWebServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BOOKWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public BookWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, BOOKWEBSERVICEIMPLSERVICE_QNAME);
    }

    public BookWebServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BOOKWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public BookWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BookWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IBookWebService
     */
    @WebEndpoint(name = "BookWebServiceImplPort")
    public IBookWebService getBookWebServiceImplPort() {
        return super.getPort(new QName("http://service.bookserviceproviderexample.com/", "BookWebServiceImplPort"), IBookWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IBookWebService
     */
    @WebEndpoint(name = "BookWebServiceImplPort")
    public IBookWebService getBookWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.bookserviceproviderexample.com/", "BookWebServiceImplPort"), IBookWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BOOKWEBSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw BOOKWEBSERVICEIMPLSERVICE_EXCEPTION;
        }
        return BOOKWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
