
package com.bookserviceproviderexample.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IBookWebService", targetNamespace = "http://service.bookserviceproviderexample.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IBookWebService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.bookserviceproviderexample.service.SearchResults>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchBooks", targetNamespace = "http://service.bookserviceproviderexample.com/", className = "com.bookserviceproviderexample.service.SearchBooks")
    @ResponseWrapper(localName = "searchBooksResponse", targetNamespace = "http://service.bookserviceproviderexample.com/", className = "com.bookserviceproviderexample.service.SearchBooksResponse")
    @Action(input = "http://service.bookserviceproviderexample.com/IBookWebService/searchBooksRequest", output = "http://service.bookserviceproviderexample.com/IBookWebService/searchBooksResponse")
    public List<SearchResults> searchBooks(
        @WebParam(name = "arg0", targetNamespace = "")
        SearchParameters arg0);

}
