
package com.jaxwsexamples.authentication;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CompanyServiceImpl", targetNamespace = "http://authentication.jaxwsexamples.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CompanyServiceImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.jaxwsexamples.authentication.Employee
     * @throws AuthenticationException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEmployeeDetails", targetNamespace = "http://authentication.jaxwsexamples.com/", className = "com.jaxwsexamples.authentication.GetEmployeeDetails")
    @ResponseWrapper(localName = "getEmployeeDetailsResponse", targetNamespace = "http://authentication.jaxwsexamples.com/", className = "com.jaxwsexamples.authentication.GetEmployeeDetailsResponse")
    @Action(input = "http://authentication.jaxwsexamples.com/CompanyServiceImpl/getEmployeeDetailsRequest", output = "http://authentication.jaxwsexamples.com/CompanyServiceImpl/getEmployeeDetailsResponse", fault = {
        @FaultAction(className = AuthenticationException_Exception.class, value = "http://authentication.jaxwsexamples.com/CompanyServiceImpl/getEmployeeDetails/Fault/AuthenticationException")
    })
    public Employee getEmployeeDetails(
        @WebParam(name = "arg0", targetNamespace = "")
        Employee arg0)
        throws AuthenticationException_Exception
    ;

}
